"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

[character]
success_symbol = "[➜](bold green)"
error_symbol   = "[➜](bold red)"

[directory]
read_only       = " 󰌾"
style           = "bold lavender"
read_only_style = "red"

[git_branch]
symbol = " "
style  = "bold mauve"

[git_commit]
tag_symbol = '  '
style      = "overlay1"

[git_status]
style = "bold red"

[git_state]
style = "bold yellow"

[cmd_duration]
style = "overlay1"

[username]
style_user = "bold peach"
style_root = "bold red"

[hostname]
ssh_symbol = " "
style      = "bold teal"

[aws]
symbol = " "

[azure]
symbol = " "

[battery]
full_symbol        = "󰁹 "
charging_symbol    = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol     = "󰂑 "
empty_symbol       = "󰂎 "

[[battery.display]]
threshold = 10
style     = "bold red"

[[battery.display]]
threshold = 30
style     = "bold yellow"

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[cobol]
symbol = " "

[conda]
symbol = " "

[container]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[direnv]
symbol = " "

[docker_context]
symbol = " "

[dotnet]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[erlang]
symbol = " "

[fennel]
symbol = " "

[fortran]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "󱇶 "

[gleam]
symbol = " "

[golang]
symbol = " "
style  = "bold teal"

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[helm]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]
symbol = "󱃾 "

[lua]
symbol = " "

[maven]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[mojo]
symbol = "󰈸 "

[nats]
symbol = " "

[netns]
symbol = "󰛳 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
style  = "bold green"

[ocaml]
symbol = " "

[odin]
symbol = "󰟢 "

[opa]
symbol = " "

[openstack]
symbol = " "

[os.symbols]
AIX           = " "
AlmaLinux     = " "
Alpaquita     = " "
Alpine        = " "
ALTLinux      = " "
Amazon        = " "
Android       = " "
AOSC          = " "
Arch          = " "
Artix         = " "
Bluefin       = " "
CachyOS       = " "
CentOS        = " "
Debian        = " "
DragonFly     = " "
Elementary    = " "
Emscripten    = " "
EndeavourOS   = " "
Fedora        = " "
FreeBSD       = " "
Garuda        = " "
Gentoo        = " "
HardenedBSD   = "󰞌 "
Illumos       = " "
InstantOS     = " "
Ios           = "󰀷 "
Kali          = " "
Linux         = " "
Mabox         = " "
Macos         = " "
Manjaro       = " "
Mariner       = " "
MidnightBSD   = " "
Mint          = " "
NetBSD        = " "
NixOS         = " "
Nobara        = " "
OpenBSD       = " "
OpenCloudOS   = " "
openEuler     = " "
openSUSE      = " "
OracleLinux   = "󰺡 "
PikaOS        = " "
Pop           = " "
Raspbian      = " "
Redhat        = "󱄛 "
RedHatEnterprise = "󱄛 "
Redox         = "󰀘 "
RockyLinux    = " "
Solus         = " "
SUSE          = " "
Ubuntu        = " "
Ultramarine   = " "
Unknown       = " "
Uos           = " "
Void          = " "
Windows       = "󰍲 "
Zorin         = " "

[package]
symbol = "󰏗 "
style  = "bold mauve"

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[pulumi]
symbol = " "

[purescript]
symbol = " "

[python]
symbol = " "
style  = "bold blue"

[raku]
symbol = "󱖊 "

[red]
symbol = "󱍼 "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "
style  = "bold peach"

[scala]
symbol = " "

[shlvl]
symbol = "󰹍 "

[singularity]
symbol = " "

[solidity]
symbol = " "

[spack]
symbol = " "

[status]
symbol = " "

[sudo]
symbol = " "

[swift]
symbol = " "

[terraform]
symbol = " "

[time]
style = "overlay1"

[vlang]
symbol = " "

[typst]
symbol = " "

[vagrant]
symbol = " "

[xmake]
symbol = " "

[zig]
symbol = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
subtext1  = "#bac2de"
subtext0  = "#a6adc8"
overlay2  = "#9399b2"
overlay1  = "#7f849c"
overlay0  = "#6c7086"
surface2  = "#585b70"
surface1  = "#45475a"
surface0  = "#313244"
base      = "#1e1e2e"
mantle    = "#181825"
crust     = "#11111b"
