"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[➜](bold #95C561)"
error_symbol   = "[➜](bold #EE6D85)"

[directory]
read_only       = " 󰌾"
style           = "bold #7199EE"
read_only_style = "#EE6D85"

[git_branch]
symbol = " "
style  = "bold #A485DD"

[git_commit]
tag_symbol = '  '
style      = "#4A5057"

[git_status]
style = "bold #EE6D85"

[git_state]
style = "bold #D7A65F"

[cmd_duration]
style = "#4A5057"

[username]
style_user = "bold #F6955B"
style_root = "bold #EE6D85"

[hostname]
ssh_symbol = " "
style      = "bold #38A89D"

[aws]
symbol = " "

[azure]
symbol = " "

[battery]
full_symbol        = "󰁹 "
charging_symbol    = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol     = "󰂑 "
empty_symbol       = "󰂎 "

[[battery.display]]
threshold = 10
style     = "bold #EE6D85"

[[battery.display]]
threshold = 30
style     = "bold #D7A65F"

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[cobol]
symbol = " "

[conda]
symbol = " "

[container]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[direnv]
symbol = " "

[docker_context]
symbol = " "

[dotnet]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[erlang]
symbol = " "

[fennel]
symbol = " "

[fortran]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "󱇶 "

[gleam]
symbol = " "

[golang]
symbol = " "
style  = "bold #38A89D"

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[helm]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]
symbol = "󱃾 "

[lua]
symbol = " "

[maven]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[mojo]
symbol = "󰈸 "

[nats]
symbol = " "

[netns]
symbol = "󰛳 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
style  = "bold #95C561"

[ocaml]
symbol = " "

[odin]
symbol = "󰟢 "

[opa]
symbol = " "

[openstack]
symbol = " "

[os.symbols]
AIX           = " "
AlmaLinux     = " "
Alpaquita     = " "
Alpine        = " "
ALTLinux      = " "
Amazon        = " "
Android       = " "
AOSC          = " "
Arch          = " "
Artix         = " "
Bluefin       = " "
CachyOS       = " "
CentOS        = " "
Debian        = " "
DragonFly     = " "
Elementary    = " "
Emscripten    = " "
EndeavourOS   = " "
Fedora        = " "
FreeBSD       = " "
Garuda        = " "
Gentoo        = " "
HardenedBSD   = "󰞌 "
Illumos       = " "
InstantOS     = " "
Ios           = "󰀷 "
Kali          = " "
Linux         = " "
Mabox         = " "
Macos         = " "
Manjaro       = " "
Mariner       = " "
MidnightBSD   = " "
Mint          = " "
NetBSD        = " "
NixOS         = " "
Nobara        = " "
OpenBSD       = " "
OpenCloudOS   = " "
openEuler     = " "
openSUSE      = " "
OracleLinux   = "󰺡 "
PikaOS        = " "
Pop           = " "
Raspbian      = " "
Redhat        = "󱄛 "
RedHatEnterprise = "󱄛 "
Redox         = "󰀘 "
RockyLinux    = " "
Solus         = " "
SUSE          = " "
Ubuntu        = " "
Ultramarine   = " "
Unknown       = " "
Uos           = " "
Void          = " "
Windows       = "󰍲 "
Zorin         = " "

[package]
symbol = "󰏗 "
style  = "bold #A485DD"

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[pulumi]
symbol = " "

[purescript]
symbol = " "

[python]
symbol = " "
style  = "bold #7199EE"

[raku]
symbol = "󱖊 "

[red]
symbol = "󱍼 "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "
style  = "bold #F6955B"

[scala]
symbol = " "

[shlvl]
symbol = "󰹍 "

[singularity]
symbol = " "

[solidity]
symbol = " "

[spack]
symbol = " "

[status]
symbol = " "

[sudo]
symbol = " "

[swift]
symbol = " "

[terraform]
symbol = " "

[time]
style = "#4A5057"

[vlang]
symbol = " "

[typst]
symbol = " "

[vagrant]
symbol = " "

[xmake]
symbol = " "

[zig]
symbol = " "
